### ISSUE TITLE
reducing min SDK

### ISSUE THREAD

**Issue by elghazal-a** [tfcporciuncula/phonemoji#1]
Is it possible to reduce the min SDK to 16?

**Comment by tfcporciuncula** [comment]
There are currently two reasons we're min SDK 21:

- So we can use [`TelephoneBuilder`](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/text/style/TtsSpan.java;l=1281) and [`TtsSpan.TYPE_TELEPHONE`](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/text/style/TtsSpan.java;drc=master;l=131) for accessibility purposes, both of them introduced on API level 21.
- So we're able to take advantage of the emoji bundled on Android, which only started to happen on API level 21.

For the first point we could simply not add a `TtsSpan` for API level < 21, compromising a bit on accessibility. And for the emoji we could use [Jetpack Emoji](https://developer.android.com/jetpack/androidx/releases/emoji) to bundle the emoji with our library, [but it still only works on API level 19 and higher](https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat#using-emojicompat-with-custom-widgets). I'm not sure there's a way to properly support emoji before API level 19, unfortunately.

You can still use the library without showing the emoji flags, though (by using the `PhonemojiTextInputEditText` directly or by setting `phonemoji_showFlag` to `false` in the `PhonemojiTextInputLayout`). But I'm not sure if it'd make sense to lower the min SDK of the library to support lower versions without the emoji, which is one of the main features of the lib. You tell me :)
