### ISSUE TITLE
Please help me to solve this error

### ISSUE THREAD

**Issue by MohsenNooriArdestani** [tfcporciuncula/phonemoji#10]
Failed to transform 'C:\Users\MOHSEN\.gradle\caches\modules-2\files-2.1\com.fredporciuncula\phonemoji\1.2.0\604184735c49475e4d56eb42c5ee0b1ada7ff7df\phonemoji-1.2.0.aar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)

**Comment by tfcporciuncula** [comment]
This doesn't really seem related to the library, so I'll just close the issue for now.
