### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by bettimms** [tfcporciuncula/phonemoji#11]
Seems like right to left is not supported when switching the language in a localized application.

**Comment by tfcporciuncula** [comment]
Everything is built upon `TextInputEditText` and `TextInputLayout`, which should have proper RTL support in place. As it's described [here](https://material.io/components/text-fields#anatomy), for instance, I can see the start icon (in our case the emoji) changing position when I run the sample in RTL.

There's nothing added by the library that should get in the way of the component's out of the box RTL support, and if you want to force the text to align on the right on RTL, you can always set `android:textAlignment="viewStart"` (or `textAlignment = EditText.TEXT_ALIGNMENT_VIEW_START` programmatically).
