### ISSUE TITLE
direct changing country code not changing flag

### ISSUE THREAD

**Issue by MuhammadSaadSiddique** [tfcporciuncula/phonemoji#14]
I checked that if we change +92 to +966 by just removing 2 and adding 66 it will not change flag.

**Comment by tfcporciuncula** [comment]
Would you mind sharing more details? I'm unable to reproduce the issue:


https://user-images.githubusercontent.com/750114/230793504-15a0ee4a-9f86-4fa8-9cfb-722428c555c4.mov

**Comment by MuhammadSaadSiddique** [comment]
no first time when we remove 2 and add different no it is not working when we remove all it will work fine.

**Comment by tfcporciuncula** [comment]
Thanks for reporting it, I think I've found and fixed the root cause. Would you be able to check if the issue is fixed in the latest release (1.5.1)?

**Comment by tfcporciuncula** [comment]
It should be fixed!
