### ISSUE TITLE
How to get Region Code?

### ISSUE THREAD

**Issue by vanhung1710** [tfcporciuncula/phonemoji#16]
We want to get region code after users type phone number manually.

**Comment by tfcporciuncula** [comment]
I can't think of a great way to expose that as an API in the library. Let's say we create a new method called `regionCode()`, what should it return if:

- The input field is empty
- The input field doesn't have a valid country code (e.g. "+422222")
- The input field only has the beginning of a valid country code (e.g. ("+5")

Is returning `null` good enough for all those different cases? It's hard to know how this API would end up being used in the end by different clients. So if you need the code my suggestion is to implement it yourself on your end and then decide how you should handle these particular cases based on your specific needs.

You can build it assuming there's always a space after the code, so something like this should work:

```kotlin
text.substringBefore(" ")
```

If you want to make sure you only get the code if it's valid, then you can check if there's a space in the string before running that.

```kotlin
if (text.contains(" ")) text.substringBefore(" ") else null
```

Note that the space is only added once an additional number is inputted after the code, so if the input is just "+1", there won't be a space in the text yet even though "1" is a valid code.

**Comment by vanhung1710** [comment]
Thanks for you feedback. I wrote this code for my purpose.
`public static PhoneNumber parsePhoneNumber(final Context context, final String phoneNumber) {
        if (TextUtils.isEmpty(phoneNumber)) return null;
        try {
            String pureNumber = purePhoneNumber(phoneNumber);
            if (phoneNumber.startsWith("+")) pureNumber = "+".concat(pureNumber);

            PhoneNumberUtil phoneNumberUtil = PhoneNumberUtil.createInstance(context);
            Phonenumber.PhoneNumber number = phoneNumberUtil.parse(phoneNumber, null);
            int countryCode = number.getCountryCode();
            String regionCode = phoneNumberUtil.getRegionCodeForCountryCode(countryCode);
            PhoneNumber result = new PhoneNumber();
            result.fullNumber = pureNumber;
            result.countryCode = countryCode;
            result.regionCode = regionCode;
            String prefix;
            if (phoneNumber.startsWith("+")) {
                prefix = "+" + countryCode;
            } else {
                prefix = "" + countryCode;
            }

            result.numberPart = pureNumber.substring(prefix.length());

            return result;
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        return null;
    }

    public static String purePhoneNumber(String str) {
        StringBuilder result = new StringBuilder();
        int len = str.length();
        for (int idx = 0; idx < len; idx++) {
            char c = str.charAt(idx);
            if (c >= '0' && c <= '9') {
                result.append(c);
            }
        }

        return result.toString();
    }

class PhoneNumber {
    public String fullNumber;
    public int countryCode = 0;
    public String regionCode = "";
    public String numberPart;
}
`
