### ISSUE TITLE
Support icon tap for list of country

### ISSUE THREAD

**Issue by SaezChristopher** [tfcporciuncula/phonemoji#3]
I think its too sad that this feature is not supported :(

**Comment by tfcporciuncula** [comment]
The main reason I don't want to support this is to keep the library lean. There's too many ways to implement this in terms of UI/UX, and it would be hard to reach a solution that is flexible enough to address all the different potential requirements different consumers would have, making it hard to justify its integration here.

It should be feasible to implement something like this on top of the library, so for now the plan is to stick to that.
