### ISSUE TITLE
[BUG] - flag is not updated on specific usecase

### ISSUE THREAD

**Issue by SaezChristopher** [tfcporciuncula/phonemoji#5]
In the sample project on line 144:
        
```xml
<com.tfcporciuncula.phonemoji.PhonemojiTextInputEditText
          android:id="@+id/secondParentlessTextInputEditText"
          android:layout_width="match_parent"
          android:layout_height="match_parent"
          android:paddingStart="28dp"
          app:phonemoji_initialRegionCode="JP" //FR
          tools:ignore="RtlSymmetry"
          />
```

if i replace JP by FR and i launch the app and then I delete the last character (a '3')  (from right to left) and i put another letters, it not update the flags and the format. It will only update the format if i delete the 2 characters (the two '3')

After digging it, it seems that if we fill default initialregion code and country so the bug is not here. Seems to be when its autodetected when no default value is filled

**Comment by tfcporciuncula** [comment]
I'm not entirely sure I understand the issue.

>and i put another letters

Are you really inputting letters or do you mean other numbers?

I think you might be experiencing [`PhoneNumberFormattingTextWatcher`](https://developer.android.com/reference/android/telephony/PhoneNumberFormattingTextWatcher)'s default behavior of [stopping formatting whenever non-dialable characters are inserted](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/telephony/java/android/telephony/PhoneNumberFormattingTextWatcher.java;l=93), and then [only restarting the formatting when the text is clear](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/telephony/java/android/telephony/PhoneNumberFormattingTextWatcher.java;l=102). This behavior is also present in [InternationalPhoneNumberFormattingTextWatcher](https://github.com/tfcporciuncula/phonemoji/blob/master/phonemoji/src/main/java/com/tfcporciuncula/phonemoji/InternationalPhoneNumberFormattingTextWatcher.kt) ([here](https://github.com/tfcporciuncula/phonemoji/blob/b45e7c12794a8e3b2e83d3e32acc440d71b818d7/phonemoji/src/main/java/com/tfcporciuncula/phonemoji/InternationalPhoneNumberFormattingTextWatcher.kt#L36) and [here](https://github.com/tfcporciuncula/phonemoji/blob/b45e7c12794a8e3b2e83d3e32acc440d71b818d7/phonemoji/src/main/java/com/tfcporciuncula/phonemoji/InternationalPhoneNumberFormattingTextWatcher.kt#L53)).

I think it would help if you try to describe the issue in more details with a step by step kind of approach.

**Comment by tfcporciuncula** [comment]
Feel free to reopen the issue with more information if needed.

**Comment by SaezChristopher** [comment]
Well done its nots fixed :p
