### ISSUE TITLE
Document the use of `androidx.startup` explicitly

### ISSUE THREAD

**Issue by Kshitij09** [tfcporciuncula/phonemoji#9]
I'm using this library and was completely unaware that it uses `androidx.startup.Initializer` to initialize the PhoneNumberUtil instance. Since I was not using the `androidx.startup` anywhere in my app, I went ahead disabling the same while following the [WorkManger: Custom Configuration ](https://developer.android.com/topic/libraries/architecture/workmanager/advanced/custom-configuration#remove-default) guide, which resulted in an app crash due to `IllegalStateException` raised [here](https://github.com/tfcporciuncula/phonemoji/blob/6739e509fc22f9752f10ae309ccadb3aec42cc62/phonemoji/src/main/java/com/fredporciuncula/phonemoji/internal/PhoneNumberUtilInstanceProvider.kt#L13)

it's pretty neat that library takes care of initialization itself 👍 
(No more "put these lines in your Application's `onCreate()`" instructions 🙂) 

and documenting the same would make it even **clearer**.

**Comment by tfcporciuncula** [comment]
[Done!](https://github.com/tfcporciuncula/phonemoji#startup)
